# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/structurizr/json/master/structurizr.yaml
#   timestamp: 2024-06-26T14:34:53+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional


@dataclass
class Enterprise:
    name: Optional[str] = None


class Location(Enum):
    External = 'External'
    Internal = 'Internal'
    Unspecified = 'Unspecified'


@dataclass
class HttpHealthCheck:
    name: Optional[str] = None
    url: Optional[str] = None
    interval: Optional[float] = None
    timeout: Optional[float] = None
    headers: Optional[Dict[str, Any]] = None


class InteractionStyle(Enum):
    Synchronous = 'Synchronous'
    Asynchronous = 'Asynchronous'


@dataclass
class Perspective:
    name: Optional[str] = None
    description: Optional[str] = None
    value: Optional[str] = None


class PaperSize(Enum):
    A6_Portrait = 'A6_Portrait'
    A6_Landscape = 'A6_Landscape'
    A5_Portrait = 'A5_Portrait'
    A5_Landscape = 'A5_Landscape'
    A4_Portrait = 'A4_Portrait'
    A4_Landscape = 'A4_Landscape'
    A3_Portrait = 'A3_Portrait'
    A3_Landscape = 'A3_Landscape'
    A2_Portrait = 'A2_Portrait'
    A2_Landscape = 'A2_Landscape'
    A1_Portrait = 'A1_Portrait'
    A1_Landscape = 'A1_Landscape'
    A0_Portrait = 'A0_Portrait'
    A0_Landscape = 'A0_Landscape'
    Letter_Portrait = 'Letter_Portrait'
    Letter_Landscape = 'Letter_Landscape'
    Legal_Portrait = 'Legal_Portrait'
    Legal_Landscape = 'Legal_Landscape'
    Slide_4_3 = 'Slide_4_3'
    Slide_16_9 = 'Slide_16_9'
    Slide_16_10 = 'Slide_16_10'


class Mode(Enum):
    Include = 'Include'
    Exclude = 'Exclude'


@dataclass
class FilteredView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    baseViewKey: Optional[str] = None
    mode: Optional[Mode] = None
    tags: Optional[List[str]] = None


@dataclass
class ImageView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    elementId: Optional[str] = None
    content: Optional[str] = None
    contentType: Optional[str] = None


@dataclass
class ElementView:
    id: Optional[str] = None
    x: Optional[float] = None
    y: Optional[float] = None


class Routing(Enum):
    Direct = 'Direct'
    Curved = 'Curved'
    Orthogonal = 'Orthogonal'


@dataclass
class Vertex:
    x: Optional[float] = None
    y: Optional[float] = None


@dataclass
class AnimationStep:
    order: Optional[float] = None
    elements: Optional[List[str]] = None
    relationships: Optional[List[str]] = None


@dataclass
class Dimensions:
    width: Optional[float] = None
    height: Optional[float] = None


class Implementation(Enum):
    Graphviz = 'Graphviz'
    Dagre = 'Dagre'


class RankDirection(Enum):
    TopBottom = 'TopBottom'
    BottomTop = 'BottomTop'
    LeftRight = 'LeftRight'
    RightLeft = 'RightLeft'


@dataclass
class AutomaticLayout:
    implementation: Optional[Implementation] = None
    rankDirection: Optional[RankDirection] = None
    rankSeparation: Optional[float] = None
    nodeSeparation: Optional[float] = None
    edgeSeparation: Optional[float] = None
    vertices: Optional[bool] = None


class MetadataSymbols(Enum):
    SquareBrackets_ = 'SquareBrackets,'
    RoundBrackets_ = 'RoundBrackets,'
    CurlyBrackets_ = 'CurlyBrackets,'
    AngleBrackets_ = 'AngleBrackets,'
    DoubleAngleBrackets_ = 'DoubleAngleBrackets,'
    None_ = 'None'


@dataclass
class Font:
    name: Optional[str] = None
    url: Optional[str] = None


@dataclass
class Branding:
    logo: Optional[str] = None
    font: Optional[Font] = None


class Shape(Enum):
    Box = 'Box'
    RoundedBox = 'RoundedBox'
    Component = 'Component'
    Circle = 'Circle'
    Ellipse = 'Ellipse'
    Hexagon = 'Hexagon'
    Diamond = 'Diamond'
    Folder = 'Folder'
    Cylinder = 'Cylinder'
    Pipe = 'Pipe'
    WebBrowser = 'WebBrowser'
    Window = 'Window'
    MobileDevicePortrait = 'MobileDevicePortrait'
    MobileDeviceLandscape = 'MobileDeviceLandscape'
    Person = 'Person'
    Robot = 'Robot'


class Border(Enum):
    Solid = 'Solid'
    Dashed = 'Dashed'
    Dotted = 'Dotted'


@dataclass
class ElementStyle:
    tag: Optional[str] = None
    width: Optional[float] = None
    height: Optional[float] = None
    background: Optional[str] = None
    stroke: Optional[str] = None
    strokeWidth: Optional[float] = None
    color: Optional[str] = None
    fontSize: Optional[float] = None
    shape: Optional[Shape] = None
    icon: Optional[str] = None
    border: Optional[Border] = None
    opacity: Optional[float] = None
    metadata: Optional[bool] = None
    description: Optional[bool] = None


@dataclass
class RelationshipStyle:
    tag: Optional[str] = None
    thickness: Optional[float] = None
    color: Optional[str] = None
    fontSize: Optional[float] = None
    width: Optional[float] = None
    dashed: Optional[bool] = None
    routing: Optional[Routing] = None
    position: Optional[float] = None
    opacity: Optional[float] = None


class Format(Enum):
    Markdown = 'Markdown'
    AsciiDoc = 'AsciiDoc'


@dataclass
class DocumentationSection:
    content: Optional[str] = None
    format: Optional[Format] = None
    order: Optional[float] = None


class Status(Enum):
    Proposed = 'Proposed'
    Accepted = 'Accepted'
    Superseded = 'Superseded'
    Deprecated = 'Deprecated'
    Rejected = 'Rejected'


@dataclass
class Decision:
    id: Optional[str] = None
    date: Optional[str] = None
    status: Optional[Status] = None
    title: Optional[str] = None
    content: Optional[str] = None
    format: Optional[Format] = None
    elementId: Optional[str] = None


@dataclass
class Image:
    name: Optional[str] = None
    content: Optional[str] = None
    type: Optional[str] = None


@dataclass
class Terminology:
    enterprise: Optional[str] = None
    person: Optional[str] = None
    softwareSystem: Optional[str] = None
    container: Optional[str] = None
    component: Optional[str] = None
    code: Optional[str] = None
    deploymentNode: Optional[str] = None
    relationship: Optional[str] = None


class Visibility(Enum):
    Public = 'Public'
    Private = 'Private'


class Scope(Enum):
    Landscape = 'Landscape'
    SoftwareSystem = 'SoftwareSystem'


class Role(Enum):
    ReadWrite = 'ReadWrite'
    ReadOnly = 'ReadOnly'


@dataclass
class User:
    username: Optional[str] = None
    role: Optional[Role] = None


@dataclass
class APIResponse:
    success: Optional[bool] = None
    message: Optional[str] = None
    revision: Optional[int] = None


@dataclass
class Relationship:
    id: Optional[str] = None
    description: Optional[str] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    sourceId: Optional[str] = None
    destinationId: Optional[str] = None
    technology: Optional[str] = None
    interactionStyle: Optional[InteractionStyle] = None
    linkedRelationshipId: Optional[str] = None


@dataclass
class RelationshipView:
    id: Optional[str] = None
    description: Optional[str] = None
    response: Optional[bool] = None
    order: Optional[str] = None
    vertices: Optional[List[Vertex]] = None
    routing: Optional[Routing] = None
    position: Optional[float] = None


@dataclass
class Styles:
    elements: Optional[List[ElementStyle]] = None
    relationships: Optional[List[RelationshipStyle]] = None


@dataclass
class Configuration:
    styles: Optional[Styles] = None
    lastSavedView: Optional[str] = None
    defaultView: Optional[str] = None
    themes: Optional[List[str]] = None
    branding: Optional[Branding] = None
    terminology: Optional[Terminology] = None
    metadataSymbols: Optional[MetadataSymbols] = None
    properties: Optional[Dict[str, Any]] = None


@dataclass
class Documentation:
    sections: Optional[List[DocumentationSection]] = None
    decisions: Optional[List[Decision]] = None
    images: Optional[List[Image]] = None


@dataclass
class WorkspaceConfiguration:
    users: Optional[List[User]] = None
    visibility: Optional[Visibility] = None
    scope: Optional[Scope] = None


@dataclass
class Person:
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    location: Optional[Location] = None
    group: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None


@dataclass
class Component:
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    technology: Optional[str] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    group: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None
    documentation: Optional[Documentation] = None


@dataclass
class InfrastructureNode:
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    technology: Optional[str] = None
    environment: Optional[str] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None


@dataclass
class SoftwareSystemInstance:
    id: Optional[str] = None
    softwareSystemId: Optional[str] = None
    instanceId: Optional[float] = None
    environment: Optional[str] = None
    tags: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None
    healthChecks: Optional[List[HttpHealthCheck]] = None


@dataclass
class ContainerInstance:
    id: Optional[str] = None
    containerId: Optional[str] = None
    instanceId: Optional[float] = None
    environment: Optional[str] = None
    tags: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None
    healthChecks: Optional[List[HttpHealthCheck]] = None


@dataclass
class SystemLandscapeView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    paperSize: Optional[PaperSize] = None
    dimensions: Optional[Dimensions] = None
    automaticLayout: Optional[AutomaticLayout] = None
    enterpriseBoundaryVisible: Optional[bool] = None
    elements: Optional[List[ElementView]] = None
    relationships: Optional[List[RelationshipView]] = None
    animations: Optional[List[AnimationStep]] = None


@dataclass
class SystemContextView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    softwareSystemId: Optional[str] = None
    paperSize: Optional[PaperSize] = None
    dimensions: Optional[Dimensions] = None
    automaticLayout: Optional[AutomaticLayout] = None
    enterpriseBoundaryVisible: Optional[bool] = None
    elements: Optional[List[ElementView]] = None
    relationships: Optional[List[RelationshipView]] = None
    animations: Optional[List[AnimationStep]] = None


@dataclass
class ContainerView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    softwareSystemId: Optional[str] = None
    paperSize: Optional[PaperSize] = None
    dimensions: Optional[Dimensions] = None
    automaticLayout: Optional[AutomaticLayout] = None
    elements: Optional[List[ElementView]] = None
    relationships: Optional[List[RelationshipView]] = None
    animations: Optional[List[AnimationStep]] = None
    externalSoftwareSystemBoundariesVisible: Optional[bool] = None


@dataclass
class ComponentView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    containerId: Optional[str] = None
    paperSize: Optional[PaperSize] = None
    dimensions: Optional[Dimensions] = None
    automaticLayout: Optional[AutomaticLayout] = None
    elements: Optional[List[ElementView]] = None
    relationships: Optional[List[RelationshipView]] = None
    animations: Optional[List[AnimationStep]] = None
    externalContainerBoundariesVisible: Optional[bool] = None


@dataclass
class DynamicView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    elementId: Optional[str] = None
    paperSize: Optional[PaperSize] = None
    dimensions: Optional[Dimensions] = None
    automaticLayout: Optional[AutomaticLayout] = None
    elements: Optional[List[ElementView]] = None
    relationships: Optional[List[RelationshipView]] = None
    externalBoundariesVisible: Optional[bool] = None


@dataclass
class DeploymentView:
    key: Optional[str] = None
    order: Optional[float] = None
    title: Optional[str] = None
    description: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    softwareSystemId: Optional[str] = None
    environment: Optional[str] = None
    paperSize: Optional[PaperSize] = None
    dimensions: Optional[Dimensions] = None
    automaticLayout: Optional[AutomaticLayout] = None
    elements: Optional[List[ElementView]] = None
    relationships: Optional[List[RelationshipView]] = None
    animations: Optional[List[AnimationStep]] = None


@dataclass
class Container:
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    technology: Optional[str] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    components: Optional[List[Component]] = None
    group: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None
    documentation: Optional[Documentation] = None


@dataclass
class DeploymentNode:
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    technology: Optional[str] = None
    environment: Optional[str] = None
    instances: Optional[str] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    children: Optional[List[DeploymentNode]] = None
    infrastructureNodes: Optional[List[InfrastructureNode]] = None
    softwareSystemInstances: Optional[List[SoftwareSystemInstance]] = None
    containerInstances: Optional[List[ContainerInstance]] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None


@dataclass
class Views:
    systemLandscapeViews: Optional[List[SystemLandscapeView]] = None
    systemContextViews: Optional[List[SystemContextView]] = None
    containerViews: Optional[List[ContainerView]] = None
    componentViews: Optional[List[ComponentView]] = None
    dynamicViews: Optional[List[DynamicView]] = None
    deploymentViews: Optional[List[DeploymentView]] = None
    filteredViews: Optional[List[FilteredView]] = None
    imageViews: Optional[List[ImageView]] = None
    configuration: Optional[Configuration] = None


@dataclass
class SoftwareSystem:
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    location: Optional[Location] = None
    tags: Optional[str] = None
    url: Optional[str] = None
    containers: Optional[List[Container]] = None
    group: Optional[str] = None
    properties: Optional[Dict[str, Any]] = None
    perspectives: Optional[List[Perspective]] = None
    relationships: Optional[List[Relationship]] = None
    documentation: Optional[Documentation] = None


@dataclass
class Model:
    enterprise: Optional[Enterprise] = None
    people: Optional[List[Person]] = None
    softwareSystems: Optional[List[SoftwareSystem]] = None
    deploymentNodes: Optional[List[DeploymentNode]] = None
    properties: Optional[Dict[str, Any]] = None


@dataclass
class Workspace:
    id: Optional[float] = None
    name: Optional[str] = None
    description: Optional[str] = None
    version: Optional[str] = None
    thumbnail: Optional[str] = None
    lastModifiedDate: Optional[str] = None
    lastModifiedUser: Optional[str] = None
    lastModifiedAgent: Optional[str] = None
    model: Optional[Model] = None
    views: Optional[Views] = None
    documentation: Optional[Documentation] = None
    configuration: Optional[WorkspaceConfiguration] = None
    properties: Optional[Dict[str, Any]] = None
