@startuml
set separator none
title Corporate Web App - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

AddElementTag("Amazon Web Services - Lambda", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#e2730e", $sprite="img:https://static.structurizr.com/themes/amazon-web-services-2023.01.31/Arch_AWS-Lambda_48.png{scale=0.46875}", $shadowing="", $borderStyle="solid")
AddElementTag("Amazon Web Services - RDS,db", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#3f51d4", $sprite="img:https://static.structurizr.com/themes/amazon-web-services-2023.01.31/Arch_Amazon-RDS_48.png{scale=0.46875}", $shadowing="", $borderStyle="solid")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")


System_Boundary("CorporateWebApp_boundary", "Corporate Web App", $tags="Element") {
  ContainerDb(CorporateWebApp.database, "database", $techn="", $descr="", $tags="Amazon Web Services - RDS,db", $link="")
  Container(CorporateWebApp.api, "api", $techn="", $descr="", $tags="Amazon Web Services - Lambda", $link="")
}

Rel(CorporateWebApp.api, CorporateWebApp.database, "Reads and writes data from/to", $techn="http/api", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml