# Publishes the package to PyPI when the PR is merged to master. Also create and push the
# git tag named after the version of the package.

name: release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Set up miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: 'latest'
        activate-environment: buildzr-dev
        environment-file: environment.yml

    - name: Install dependencies for building the package
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build

    - name: Install hatch
      uses: pypa/hatch@install

    - name: Determine version bump
      id: version
      run: |
        # Note: May not work as expected if this repo has only one commit.
        LAST_TAG=$(git describe --tags --abbrev=0 2&>/dev/null || echo HEAD~1)
        COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:"%s%n%b")

        # -- MAJORS --
        if echo "$COMMITS" | grep -q "BREAKING CHANGE:"; then
          echo "major"
          echo "major" >> $GITHUB_OUTPUT

        # -- MINORS --
        elif echo "$COMMITS" | grep -q "feat"; then
          echo "minor"
          echo "minor" >> $GITHUB_OUTPUT

        # -- PATCHES --
        elif echo "$COMMITS" | grep -q "fix"; then
          echo "patch"
          echo "patch" >> $GITHUB_OUTPUT
        elif echo "$COMMITS" | grep -q "ci"; then
          echo "patch"
          echo "patch" >> $GITHUB_OUTPUT

        # -- NO BUMP --
        else
          echo "No version bump keyword found."
          exit 1
        fi

    - name: Bump release version
      run: |
        hatch version ${{ steps.version.outputs.version }}
        NEW_VERSION=`hatch version`
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add buildzr/__about__.py
        git commit -m "[skip-ci] Bump version to $NEW_VERSION"
        git tag $NEW_VERSION
        git push
        git push --tags

    - name: Build package
      run: |
        python -m build

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}