# Publishes the package to PyPI when the PR is merged to master. Also create and push the
# git tag named after the version of the package.

name: release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Set up miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: 'latest'
        activate-environment: buildzr-dev
        environment-file: environment.yml

    - name: Install dependencies for building the package
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build

    - name: Install hatch
      uses: pypa/hatch@install

    - name: Release version
      run: |
        hatch version release
        NEW_VERSION=`hatch version`
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add buildzr/__about__.py
        git commit -m "[skip-ci] Bump version to $NEW_VERSION"
        git tag $NEW_VERSION
        git push
        git push origin:master --tags

    - name: Build package
      run: |
        python -m build

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}