# Publishes the package to PyPI when the PR is merged to master. Also create and push the
# git tag named after the version of the package.

name: release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Download build from pre-release
      uses: actions/download-artifact@v4
      with:
        name: build
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}