name: prerelease

on:
  push:
    branches:
      - fix/release-workflow-target

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies for building the package
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Hatch
      uses: pypa/hatch@install

    - name: Update Version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url --push origin https://amirulmenjeni:${GITHUB_TOKEN}@github.com/amirulmenjeni/buildzr.git

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        hatch version release
        NEW_VERSION=$(hatch version)
        git add buildzr/__about__.py
        git commit -m "ci: [skip-ci] Update version to $NEW_VERSION"

        git tag $NEW_VERSION
        git push origin ${{ github.ref}}
        git push origin ${{ github.ref }} --tags

        # Do nothing. See how it behave.

    - name: Build package
      run: |
        python -m build

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist/

    # - name: Publish package to PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}